(()=>{
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const form=o=>window.tcOpenRecordForm?window.tcOpenRecordForm(o):alert('Form engine unavailable.');
 const p=()=>typeof currentProject==='function'?currentProject():null;
 const id=(prefix,arr)=>`${prefix}-${String((arr||[]).length+1).padStart(3,'0')}`;
 function addSchedule(){const prj=p();if(!prj)return;form({title:'Add Schedule Activity',subtitle:prj.name,fields:[{name:'activityId',label:'Activity ID',value:id('A',state.schedule?.activities),required:true},{name:'activity',label:'Activity',required:true},{name:'plannedStart',label:'Planned Start',type:'date'},{name:'plannedFinish',label:'Planned Finish',type:'date'},{name:'predecessor',label:'Predecessor Activity ID'},{name:'percent',label:'Percent Complete',type:'number',value:'0'},{name:'critical',label:'Critical?',type:'select',options:['No','Yes']}],onSave:async d=>{state.schedule=state.schedule||{versions:[],activities:[]};state.schedule.activities.push({project:prj.name,id:d.activityId,activity:d.activity,planned:+d.percent||0,actual:+d.percent||0,status:+d.percent>=100?'Complete':+d.percent>0?'Active':'Not Started',critical:d.critical==='Yes',plannedStart:d.plannedStart,plannedFinish:d.plannedFinish,predecessor:d.predecessor});save('Added schedule activity',d.activity)}})}
 function addProcurement(){const prj=p();if(!prj)return;form({title:'Add Procurement Item',subtitle:prj.name,fields:[{name:'item',label:'Item / Package',required:true},{name:'sub',label:'Vendor / Subcontractor'},{name:'status',label:'Status',type:'select',options:['Planned','Submittal Pending','A/E Review','Approved','Released','Fabrication','Shipped','Delivered','Installed']},{name:'required',label:'Required on Site',type:'date'},{name:'lead',label:'Lead Time'},{name:'activity',label:'Linked Schedule Activity'}],onSave:async d=>{state.procurement=state.procurement||[];state.procurement.push({project:prj.name,...d});save('Added procurement item',d.item)}})}
 function addCorrespondence(kind){const prj=p();if(!prj)return;const external=kind==='external';form({title:external?'Compose External Message':'New Internal Message',subtitle:prj.name,fields:[{name:'subject',label:'Subject',required:true},{name:'to',label:external?'To / Distribution':'Internal Distribution',required:true},{name:'linked',label:'Linked Record'},{name:'body',label:'Message',type:'textarea',rows:7,required:true}],onSave:async d=>{const rec={project:prj.name,date:new Date().toISOString().slice(0,10),subject:d.subject,from:currentUser?.name||'User',to:d.to,linked:d.linked||'',status:'Sent',body:d.body};if(external){state.externalMessages=state.externalMessages||[];state.externalMessages.push(rec)}else{state.internalMessages=state.internalMessages||[];state.internalMessages.push({...rec,visibility:'Company Only'})}save('Created correspondence',d.subject)}})}
 function addPayApp(){const prj=p();if(!prj)return;state.payapps=state.payapps||{};if(!state.payapps[prj.name])state.payapps[prj.name]={number:1,prior:0,retainage:10,rows:[]};form({title:'Add Pay App SOV Line',subtitle:prj.name,fields:[{name:'sov',label:'Schedule of Values Item',required:true},{name:'value',label:'Scheduled Value',type:'number',required:true}],onSave:async d=>{state.payapps[prj.name].rows.push({sov:d.sov,value:+d.value||0,prev:0,current:0,stored:0});save('Added pay app SOV line',d.sov)}})}
 function addContract(){const prj=p();if(!prj)return;form({title:'Add Subcontract / Commitment',subtitle:prj.name,fields:[{name:'company',label:'Company',required:true},{name:'trade',label:'Trade / CSI',required:true},{name:'value',label:'Contract Value',type:'number'},{name:'expires',label:'COI Expires',type:'date'},{name:'status',label:'Compliance',type:'select',options:['Current','Pending','Expired','On Hold']}],onSave:async d=>{state.contracts=state.contracts||[];state.contracts.push({project:prj.name,company:d.company,trade:d.trade,value:+d.value||0,expires:d.expires,cgl:'TBD',auto:'TBD',wc:'TBD',umbrella:'TBD',status:d.status});save('Added subcontract',d.company)}})}
 function addWarrantyButton(){const root=$('#warranty');if(!root)return;const b=[...root.querySelectorAll('button')].find(x=>/Warranty|Asset/.test(x.textContent));if(b&&window.tcAddWarranty)b.onclick=window.tcAddWarranty}
 function openProjectByName(name,page='home'){const prj=(state.projects||[]).find(x=>x.name===name);if(!prj)return;const sel=$('#projectSelect');if(sel)sel.value=prj.id;if(typeof refreshBanner==='function')refreshBanner();if(typeof renderPage==='function')renderPage(page);currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
 function wireDrilldowns(){
  $$('.project-card').forEach(c=>{if(c.dataset.r1drill)return;c.dataset.r1drill='1';c.onclick=()=>{const h=c.querySelector('h4');if(h)openProjectByName(h.textContent.trim(),'home')}});
  $$('#wip tr.clickable,#projectboard tr.clickable').forEach(r=>{if(r.dataset.r1drill)return;r.dataset.r1drill='1';r.onclick=()=>{const name=r.cells?.[0]?.innerText?.trim()||r.querySelector('b')?.textContent?.trim();if(name)openProjectByName(name,'home')}});
 }
 function wire(){
  const mappings=[['#schedule','Activity',addSchedule],['#procurement','Procurement',addProcurement],['#payapps','Pay',addPayApp],['#contracts','Contract',addContract]];
  mappings.forEach(([root,text,fn])=>{const el=$(root);if(!el)return;[...el.querySelectorAll('button')].filter(b=>b.textContent.includes('+')&&b.textContent.toLowerCase().includes(text.toLowerCase())).forEach(b=>b.onclick=fn)});
  const ni=$('#newInternal');if(ni)ni.onclick=()=>addCorrespondence('internal');const ne=$('#newExternal');if(ne)ne.onclick=()=>addCorrespondence('external');
  addWarrantyButton();wireDrilldowns();
 }
 window.tcOpenProject=openProjectByName;
 new MutationObserver(wire).observe(document.documentElement,{subtree:true,childList:true});addEventListener('DOMContentLoaded',wire);setTimeout(wire,500);
})();