const fs = require('fs');
const path = require('path');

module.exports = function handler(req,res){
  try{
    const htmlPath=path.join(process.cwd(),'index.html');
    let html=fs.readFileSync(htmlPath,'utf8');
    const config={
      url:process.env.NEXT_PUBLIC_SUPABASE_URL||'',
      key:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'',
      buildSha:process.env.VERCEL_GIT_COMMIT_SHA||process.env.GIT_COMMIT_SHA||'local'
    };
    const files=['r1-training-isolation.js','r1-ui.js','r1-notifications.js','r1-workflows.js','r1-finance.js','r1-training-finance-gate.js','r1-admin.js','r1-invite-secure.js','r1-invite-status.js','r1-operational2.js','r1-actions.js','r1-accounting.js','r1-field.js','r1-field-evidence-documents.js','r1-field-record-attachments.js','r1-quality-inspections.js','r1-hardening.js','r1-cloud.js','r1-training-company-sandbox.js','r1-persistence.js','r1-security.js','r1-globalcreate.js','r1-role-test.js','r1-action-guard.js','r1-acceptance.js','r1-release-gate.js','r1-feedback-center.js','r1-feedback-cloud.js','r1-feedback-attachments.js','r1-project-drilldown.js','r1-branding.js','r1-entry-ux.js','r1-professional-forms.js','r1-document-import.js','r1-contract-intelligence-live.js','r1-template-library.js','r1-form-renderers.js','r1-module-forms.js','r1-print-bridge.js','r1-package-controls.js','r1-workflow-gates.js','r1-record-lifecycle.js','r1-change-controls.js','r1-subcontract-workflow.js','r1-subcontract-readiness-detail.js','r1-readiness-detail.js','r1-ai-intake-review.js','r1-batch-bid-noi.js','r1-bid-revision-control.js','r1-scope-generation.js','r1-noi-negotiation.js','r1-subcontract-assembly.js','r1-subcontract-issue-package.js','r1-preissue-contract-check.js','r1-subcontract-execution-lifecycle.js','r1-post-execution-controls.js','r1-sub-payapp-controls.js','r1-sub-payapp-hardening.js','r1-sov-payapp.js','r1-g702-g703.js','r1-subcontractor-portal-financials.js','r1-secure-subcontractor-portal.js','r1-subcontractor-invite.js','r1-subcontractor-portal-lifecycle.js','r1-subcontractor-portal-submissions.js','r1-submission-review-queue.js','r1-document-intelligence.js','r1-document-indexer.js','r1-drawing-workspace.js','r1-drawing-upload-live.js','r1-markup-canvas.js','r1-asbuilt-verification.js','r1-asbuilt-overlay.js','r1-asbuilt-multilayer.js','r1-asbuilt-layer-review.js','r1-asbuilt-evidence.js','r1-record-drawing-closeout.js','r1-record-evidence-provenance.js','r1-record-set-output.js','r1-closeout-readiness.js','r1-closeout-package.js','r1-warranty-assets.js','r1-warranty-milestones.js','r1-warranty-notices.js','r1-warranty-correspondence.js','r1-warranty-dashboard.js','r1-warranty-permissions.js','r1-owner-warranty-portal.js','r1-owner-portal-access.js','r1-owner-portal-session.js','r1-project-archive.js','r1-archive-lock-freeze.js','r1-suite-integration.js','r1-legacy-action-guard.js','r1-verify.js','r1-legacy-surface.js'];
    const coreFiles=['r1-training-isolation.js','r1-ui.js','r1-notifications.js','r1-security.js','r1-project-drilldown.js'];
    // Route groups intentionally contain only modules proven not to self-trigger infinite DOM mutation loops.
    // Heavier render/observer modules stay deferred until their observers are hardened.
    const routeGroups={
      drawings:['r1-drawing-upload-live.js'],
      contracts:['r1-document-import.js','r1-contract-intelligence-live.js'],
      financials:['r1-finance.js'],
      payapps:['r1-sov-payapp.js','r1-g702-g703.js'],
      preconstruction:[]
    };
    const loader=`<script>\nwindow.__TC_R1_FILES__=${JSON.stringify(files)};\nwindow.__TC_R1_CORE__=${JSON.stringify(coreFiles)};\nwindow.__TC_R1_ROUTE_GROUPS__=${JSON.stringify(routeGroups)};\nwindow.tcLoadR1Modules=(function(){\n  const loaded=new Set();\n  let queue=Promise.resolve();\n  const yieldUI=()=>new Promise(resolve=>setTimeout(resolve,16));\n  const loadScript=(src)=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error('Unable to load '+src));document.body.appendChild(s)});\n  return function(list){\n    const requested=Array.isArray(list)&&list.length?list:window.__TC_R1_CORE__;\n    queue=queue.then(async()=>{\n      for(const f of requested){\n        if(loaded.has(f))continue;\n        window.__TC_R1_LOADING__=f;\n        await loadScript('/'+f);\n        loaded.add(f);\n        await yieldUI();\n      }\n      window.__TC_R1_LOADING__='';\n      window.dispatchEvent(new CustomEvent('tc:r1-ready',{detail:{loaded:[...loaded]}}));\n      return [...loaded];\n    });\n    return queue;\n  };\n})();\nwindow.tcLoadR1FullWorkspace=()=>window.tcLoadR1Modules(window.__TC_R1_FILES__);\nwindow.tcLoadDocumentLibraries=(function(){\n  let promise=null;\n  const loadScript=(src)=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Unable to load '+src));document.body.appendChild(s)});\n  return function(){if(promise)return promise;promise=Promise.all([loadScript('https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js'),loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js')]).then(()=>{if(window.pdfjsLib)window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';return true});return promise};\n})();\nwindow.tcLoadR1ForPage=async function(page){\n  const group=window.__TC_R1_ROUTE_GROUPS__?.[page];if(!group||!group.length)return [];\n  if(page==='drawings'||page==='contracts'||page==='financials')await window.tcLoadDocumentLibraries();\n  const loaded=await window.tcLoadR1Modules(group);\n  try{window.refreshBanner?.()}catch(e){console.warn('Route enhancement render',page,e)}\n  return loaded;\n};\n<\/script>`;
    const afterLive=`<script>\n(function(){\n  const bind=()=>{\n    const btn=document.getElementById('tcLoginBtn');\n    if(!btn||btn.dataset.tcLazyBound)return;\n    const original=btn.onclick;\n    if(typeof original!=='function')return;\n    btn.dataset.tcLazyBound='1';\n    btn.onclick=async function(e){\n      btn.disabled=true;\n      const msg=document.getElementById('tcLoginMsg');\n      try{\n        await original.call(this,e);\n        if(document.getElementById('app')&&!document.getElementById('app').classList.contains('hidden')){\n          if(msg)msg.textContent='Preparing TotalConstruct workspace…';\n          await window.tcLoadR1Modules(window.__TC_R1_CORE__);\n          try{window.renderAll?.();window.refreshBanner?.()}catch(err){console.warn('R1 post-load render',err)}\n          if(msg)msg.textContent='';\n        }\n      }catch(err){\n        if(msg){msg.textContent=err.message||'Unable to prepare workspace.';msg.style.color='#b9382e'}\n      }finally{btn.disabled=false}\n    };\n  };\n  const routeBind=()=>{\n    if(document.documentElement.dataset.tcRouteLoader)return;document.documentElement.dataset.tcRouteLoader='1';\n    document.addEventListener('click',e=>{const el=e.target.closest?.('[data-page],[data-jump],.nav');if(!el)return;const page=el.dataset.page||el.dataset.jump;if(page&&window.__TC_R1_ROUTE_GROUPS__?.[page]?.length)setTimeout(()=>window.tcLoadR1ForPage(page).catch(err=>window.tcNotify?.(err.message||String(err),{type:'error',title:'Module Load Failed'})),0)},true);\n  };\n  bind();routeBind();\n  addEventListener('DOMContentLoaded',()=>{bind();routeBind()},{once:true});\n})();\n<\/script>`;
    const inject=`\n<link rel="stylesheet" href="/r1-ui.css">\n<link rel="stylesheet" href="/r1-responsive-nav.css">\n<script>window.__TC_SUPABASE__=${JSON.stringify(config)};<\/script>\n${loader}\n<script src="/live.js"><\/script>\n${afterLive}\n`;
    html=html.replace('</body>',inject+'</body>');
    res.setHeader('Content-Type','text/html; charset=utf-8');
    res.setHeader('Cache-Control','no-store, max-age=0');
    res.status(200).send(html);
  }catch(err){
    res.status(500).send('TotalConstruct bootstrap error: '+err.message);
  }
};