const fs = require('fs');
const path = require('path');

module.exports = function handler(req,res){
  try{
    const htmlPath=path.join(process.cwd(),'index.html');
    let html=fs.readFileSync(htmlPath,'utf8');
    const config={
      url:process.env.NEXT_PUBLIC_SUPABASE_URL||'',
      key:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'',
      buildSha:process.env.VERCEL_GIT_COMMIT_SHA||process.env.GIT_COMMIT_SHA||'local'
    };
    const files=['r1-training-isolation.js','r1-ui.js','r1-notifications.js','r1-workflows.js','r1-finance.js','r1-training-finance-gate.js','r1-admin.js','r1-invite-secure.js','r1-invite-status.js','r1-operational2.js','r1-actions.js','r1-accounting.js','r1-field.js','r1-field-evidence-documents.js','r1-field-record-attachments.js','r1-quality-inspections.js','r1-hardening.js','r1-cloud.js','r1-training-company-sandbox.js','r1-persistence.js','r1-security.js','r1-globalcreate.js','r1-role-test.js','r1-action-guard.js','r1-acceptance.js','r1-release-gate.js','r1-feedback-center.js','r1-feedback-cloud.js','r1-feedback-attachments.js','r1-project-drilldown.js','r1-branding.js','r1-entry-ux.js','r1-professional-forms.js','r1-document-import.js','r1-template-library.js','r1-form-renderers.js','r1-module-forms.js','r1-print-bridge.js','r1-package-controls.js','r1-workflow-gates.js','r1-record-lifecycle.js','r1-change-controls.js','r1-subcontract-workflow.js','r1-subcontract-readiness-detail.js','r1-readiness-detail.js','r1-ai-intake-review.js','r1-batch-bid-noi.js','r1-bid-revision-control.js','r1-scope-generation.js','r1-noi-negotiation.js','r1-subcontract-assembly.js','r1-subcontract-issue-package.js','r1-preissue-contract-check.js','r1-subcontract-execution-lifecycle.js','r1-post-execution-controls.js','r1-sub-payapp-controls.js','r1-sub-payapp-hardening.js','r1-sov-payapp.js','r1-g702-g703.js','r1-subcontractor-portal-financials.js','r1-secure-subcontractor-portal.js','r1-subcontractor-invite.js','r1-subcontractor-portal-lifecycle.js','r1-subcontractor-portal-submissions.js','r1-submission-review-queue.js','r1-document-intelligence.js','r1-document-indexer.js','r1-delta-intelligence.js','r1-drawing-workspace.js','r1-markup-canvas.js','r1-asbuilt-verification.js','r1-asbuilt-overlay.js','r1-asbuilt-multilayer.js','r1-asbuilt-layer-review.js','r1-asbuilt-evidence.js','r1-record-drawing-closeout.js','r1-record-evidence-provenance.js','r1-record-set-output.js','r1-closeout-readiness.js','r1-closeout-package.js','r1-warranty-assets.js','r1-warranty-milestones.js','r1-warranty-notices.js','r1-warranty-correspondence.js','r1-warranty-dashboard.js','r1-warranty-permissions.js','r1-owner-warranty-portal.js','r1-owner-portal-access.js','r1-owner-portal-session.js','r1-project-archive.js','r1-archive-lock-freeze.js','r1-suite-integration.js','r1-legacy-action-guard.js','r1-verify.js','r1-legacy-surface.js'];
    const loader=`<script>\nwindow.__TC_R1_FILES__=${JSON.stringify(files)};\nwindow.tcLoadR1Modules=(function(){\n  let promise=null;\n  const yieldUI=()=>new Promise(resolve=>setTimeout(resolve,0));\n  const loadScript=(src)=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error('Unable to load '+src));document.body.appendChild(s)});\n  return function(){\n    if(promise)return promise;\n    promise=(async()=>{\n      for(const f of window.__TC_R1_FILES__){await loadScript('/'+f);await yieldUI();}\n      window.dispatchEvent(new CustomEvent('tc:r1-ready'));\n      return true;\n    })();\n    return promise;\n  };\n})();\nwindow.tcLoadDocumentLibraries=(function(){\n  let promise=null;\n  const loadScript=(src)=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Unable to load '+src));document.body.appendChild(s)});\n  return function(){if(promise)return promise;promise=Promise.all([loadScript('https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js'),loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js')]).then(()=>{if(window.pdfjsLib)window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';return true});return promise};\n})();\n<\/script>`;
    const afterLive=`<script>\n(function(){\n  const bind=()=>{\n    const btn=document.getElementById('tcLoginBtn');\n    if(!btn||btn.dataset.tcLazyBound)return;\n    const original=btn.onclick;\n    if(typeof original!=='function')return;\n    btn.dataset.tcLazyBound='1';\n    btn.onclick=async function(e){\n      btn.disabled=true;\n      const msg=document.getElementById('tcLoginMsg');\n      try{\n        await original.call(this,e);\n        if(document.getElementById('app')&&!document.getElementById('app').classList.contains('hidden')){\n          if(msg)msg.textContent='Preparing TotalConstruct workspace…';\n          await window.tcLoadR1Modules();\n          try{window.renderAll?.();window.refreshBanner?.()}catch(err){console.warn('R1 post-load render',err)}\n        }\n      }catch(err){\n        if(msg){msg.textContent=err.message||'Unable to prepare workspace.';msg.style.color='#b9382e'}\n      }finally{btn.disabled=false}\n    };\n  };\n  bind();\n  addEventListener('DOMContentLoaded',bind,{once:true});\n})();\n<\/script>`;
    const inject=`\n<link rel="stylesheet" href="/r1-ui.css">\n<script>window.__TC_SUPABASE__=${JSON.stringify(config)};<\/script>\n${loader}\n<script src="/live.js"><\/script>\n${afterLive}\n`;
    html=html.replace('</body>',inject+'</body>');
    res.setHeader('Content-Type','text/html; charset=utf-8');
    res.setHeader('Cache-Control','no-store, max-age=0');
    res.status(200).send(html);
  }catch(err){
    res.status(500).send('TotalConstruct bootstrap error: '+err.message);
  }
};