const MAX_TEXT=180000;
const ALLOWED=['application/pdf','text/plain','text/csv','application/json'];
function send(res,status,obj){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(obj))}
async function verifyUser(req){const base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!base||!token)return null;const r=await fetch(base.replace(/\/$/,'')+'/auth/v1/user',{headers:{Authorization:'Bearer '+token,apikey:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||''}});if(!r.ok)return null;return r.json()}
function prompt(files){return `You are TotalConstruct OS Project Intake. Extract only facts explicitly supported by the supplied project documents. Never infer or invent a detailed CSI/cost-code budget. If no SOV, GMP schedule, or cost breakdown supports a detailed budget, budgetStatus must be "Detailed Budget Required". Return JSON only with shape {"data":{"name":"","address":"","owner":"","contractValue":"","contractType":"","startDate":"","completionDate":"","retainage":"","paymentTerms":"","architect":"","engineer":"","description":"","staffing":"","insurance":"","bonding":"","allowances":"","notices":"","schedule":"","budgetStatus":""},"sources":{"field":{"document":"","page":"","quote":"","confidence":0}},"warnings":[]}. Confidence is 0-1. Unsupported fields must be empty and omitted from sources. Preserve exact contractual meaning. Documents:\n\n${files.map((f,i)=>`--- DOCUMENT ${i+1}: ${f.name} ---\n${String(f.text||'').slice(0,MAX_TEXT/files.length)}`).join('\n\n')}`}
module.exports=async function(req,res){try{if(req.method!=='POST')return send(res,405,{error:'POST required'});const user=await verifyUser(req);if(!user)return send(res,401,{error:'Authenticated TotalConstruct session required'});const key=process.env.OPENAI_API_KEY;if(!key)return send(res,503,{error:'AI project intake is not configured'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const files=Array.isArray(body.files)?body.files:[];if(!files.length)return send(res,400,{error:'At least one extracted document is required'});let total=0;for(const f of files){if(!f||typeof f.name!=='string'||typeof f.text!=='string')return send(res,400,{error:'Invalid document payload'});total+=f.text.length;if(total>MAX_TEXT)return send(res,413,{error:'Document text exceeds intake limit'});if(f.type&&!ALLOWED.includes(f.type)&&!/^text\//.test(f.type))return send(res,415,{error:'Unsupported extracted document type: '+f.type})}
const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_PROJECT_INTAKE_MODEL||'gpt-5-mini',input:prompt(files),text:{format:{type:'json_object'}},store:false})});const raw=await ai.json();if(!ai.ok)return send(res,502,{error:'AI intake service failed',detail:raw?.error?.message||'Unknown provider error'});const text=raw.output_text||raw.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text;if(!text)return send(res,502,{error:'AI intake returned no structured result'});let out;try{out=JSON.parse(text)}catch{return send(res,502,{error:'AI intake returned invalid structured data'})}out.data=out.data&&typeof out.data==='object'&&!Array.isArray(out.data)?out.data:{};out.sources=out.sources&&typeof out.sources==='object'&&!Array.isArray(out.sources)?out.sources:{};out.warnings=Array.isArray(out.warnings)?out.warnings:[];
// Fail closed: reject unsupported extracted fields rather than trusting AI self-reported confidence.
const sourceDocuments=new Map(files.map(f=>[f.name,String(f.text||'')]));
const normalize=s=>String(s||'').replace(/\\s+/g,' ').trim().toLowerCase();
const verified={};const safeSources={};
for(const [field,value] of Object.entries(out.data)){
 if(field==='budgetStatus')continue;
 if(value==null||String(value).trim()==='')continue;
 const source=out.sources[field];
 const documentText=sourceDocuments.get(source?.document);
 const quote=String(source?.quote||'').trim();
 const confidence=Number(source?.confidence);
 const exact=!!documentText&&quote.length>=8&&normalize(documentText).includes(normalize(quote));
 const supported=exact&&Number.isFinite(confidence)&&confidence>=0.8;
 if(!supported){out.warnings.push('AI field '+field+' withheld: source quote, document match, or confidence could not be verified.');continue}
 verified[field]=value;safeSources[field]={document:source.document,page:source.page||'',quote,confidence};
}
out.data={...verified,budgetStatus:out.data.budgetStatus||'Detailed Budget Required'};
out.sources=safeSources;
out.validation={verifiedFields:Object.keys(verified).length,withheldFields:out.warnings.filter(x=>String(x).includes(' withheld:')).length,policy:'Only source-quoted high-confidence proposals returned; human approval required.'};if(!out.data.budgetStatus)out.data.budgetStatus='Detailed Budget Required';out.reviewRequired=true;out.extractedBy='TotalConstruct AI Project Intake';out.userId=user.id;return send(res,200,out)}catch(e){console.error('project-intake',e);return send(res,500,{error:'Project intake failed safely'})}}
